### ISSUE TITLE
Re-export non descendant attribute?

### ISSUE THREAD

**Issue by vnmabus** [scientific-python/lazy_loader#27]
I have tried to use this module. However I don't think that it is possible to lazily re-export an attribute from a module that is not a direct descendant, is it?

Example:
```python
import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    __name__,
    submod_attrs={
        ".._utils": ["my_function"],
    },
)
```

**Comment by stefanv** [comment]
No, that is not currently supported; we could consider a PR if it's not too complicated. I think the easier thing to do would be to define that lazy import in the parent submodule.
