### ISSUE TITLE
Type hints/Mypy best practices?

### ISSUE THREAD

**Issue by vnmabus** [scientific-python/lazy_loader#28]
Unfortunately it seems that Mypy cannot obtain the information to type lazy imports using this module. The only way that I found to work around this is to REPEAT the imports in a `if TYPE_CHECKING` block, which honestly feels like a defeat. Is there any other way to "play well to Mypy" using this package?

**Comment by nstarman** [comment]
Followup: using numpy's mypy plugin as a reference, I specced out a quick mypy plugin (see https://github.com/nstarman/lazy_loader/tree/mypy_plugin) and unfortunately it doesn't look like there's an easy replacement to the `pyi` file.
If this package mandated that a single import be included, then I think I know how to overload that import and add on the contents of `lazy_loader.attach`:

```
from . import ...   # THIS IS MANDATORY
import lazy_loader as _lazy_loader

..., __all__ = _lazy_loader.attach(...)
```

Short of that, I haven't grokked out how to inject a new import line.

**Comment by stefanv** [comment]
@nstarman It looks to me like this may warrant a new issue. I'm going to close this one (since it's been resolved), but feel free to open another issue for the mypy plugin discussion.
