### ISSUE TITLE
conda upload

### ISSUE THREAD

**Issue by nstarman** [scientific-python/lazy_loader#33]
Is https://anaconda.org/conda-forge/lazy_loader this package?

**Comment by stefanv** [comment]
Looks like it, but it's outdated. @bmcfee, is this yours?

**Comment by stefanv** [comment]
I see @sugatoray is listed as the maintainer.

**Comment by bmcfee** [comment]
No - my PR for the 0.1 release has not yet merged https://github.com/conda-forge/lazy_loader-feedstock/pull/1

**Comment by sugatoray** [comment]
@bmcfee Thank you for your PR. I merged it. You are now a co-maintainer on the repository.

**Comment by nstarman** [comment]
Maybe https://github.com/OpenAstronomy/github-actions-workflows#build-and-publish-a-pure-python-package is useful for releasing to both pip and conda simultaneously.

**Comment by stefanv** [comment]
@hmaarrfk You indicated some interest in packaging lazy_loader? We are about to make a new release.

**Comment by hmaarrfk** [comment]
I can help but given the nature as a pure python package, i would simply add a bot automerge, and mostly forget about it.

Major changes and dependency changes should get caught by the `pip check` command that is already in place
https://github.com/conda-forge/lazy_loader-feedstock/blob/main/recipe/meta.yaml#L30


https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge

I'm on conda-forge core, so I have the ability to help in the case that the existing maintainers are busy for whatever reason. Given the existence of maintainers, I don't see the need to get involved unless there are any challenges.

**Comment by hmaarrfk** [comment]
For example, I maintain an other package that is pure python, that I just added automerge to due to hte fact that i've often failed to keep up with releases:
https://github.com/conda-forge/sphinx-copybutton-feedstock/issues/21

**Comment by hmaarrfk** [comment]
I see the conda-forge maintainers are already on this thread. Thank you both!

**Comment by stefanv** [comment]
OK, thanks Mark! In that case I think we can close this issue.

**Comment by hmaarrfk** [comment]
To be honest, i'm not sure how concerned you are about modern scikit-image making it to the defaults channel.

The explosion in tools that help improve packaging has made dependencies grow in recent years, and anaconda has lagged behind more and more it seems.

If you (we) care about being in the default channel, i would monitor:
https://anaconda.org/main/scikit-image

and try to ping anaconda when you feel it is appropriate.

**Comment by stefanv** [comment]
We don't typically interfere with company distributions. Would you say it's correct for us to focus predominantly on PyPi and conda-forge?

**Comment by hmaarrfk** [comment]
I agree with the choice not to interfere.

I just wanted to bring it up.
