### ISSUE TITLE
Help to packaging Debian package

### ISSUE THREAD

**Issue by yuzibo** [scientific-python/lazy_loader#35]
Hi, I am packaging the project into Debian, But I have unclear to me.(I am new to Debian also；）)

Generally, the python project has its own setup.py, then On Debian it can be used `pybuild`, like:
```bash
# cat debian/rule
#!/usr/bin/make -f
# You must remove unused comment lines for the released package.
#export DH_VERBOSE = 1
#export DEB_BUILD_MAINT_OPTIONS = hardening=+all
#export DEB_CFLAGS_MAINT_APPEND  = -Wall -pedantic
#export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed

%:
	dh $@ --with python3 --buildsystem=pybuild

```
But this is not work for the project. The log is:
```bash
Command: dpkg-buildpackage --sanitize-env -us -uc -rfakeroot
dpkg-buildpackage: info: source package lazy-loader
dpkg-buildpackage: info: source version 0.1-1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by vimer <tsu.yubo@gmail.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
        install -d /<<PKGBUILDDIR>>/debian/.debhelper/generated/_source/home
        pybuild --clean -i python{version} -p 3.10
E: pybuild pybuild:127: cannot detect build system, please use --system option or set PYBUILD_SYSTEM env. variable
dh_auto_clean: error: pybuild --clean -i python{version} -p 3.10 returned exit code 11
make: *** [debian/rules:9: clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2

```
But I can install it with `pip install -U lazy_loader`.
Can you tell me what build system was used in the project? Maybe I haven't learned it yet.
Thanks in advance

**Comment by stefanv** [comment]
We are using pyproject.toml. Please see https://manpages.debian.org/unstable/dh-python/pybuild.1.en.html#flit_plugin

**Comment by yuzibo** [comment]
@stefanv thanks. right, it can be built now.:)
 will close this until finishing the work.

**Comment by yuzibo** [comment]
hmm, Can I get your mail address? The d/copyright need author of the project info. Certainly, I listed Scientific Python Developers in here, But I guess this is not enough.

**Comment by stefanv** [comment]
You can use stefanv at berkeley.edu, thanks.

**Comment by stefanv** [comment]
We now have tagged releases on GitHub, which should be helpful to Debian as well.

**Comment by yuzibo** [comment]
Oh,sorry, I forget to close the issue when I have done work.:(

> We now have tagged releases on GitHub, which should be helpful to Debian as well.
Thanks again here.:)

**Comment by 78w** [comment]
> We are using pyproject.toml. Please see https://manpages.debian.org/unstable/dh-python/pybuild.1.en.html#flit_plugin我们正在使用 pyproject.toml。请参阅 https://manpages.debian.org/unstable/dh-python/pybuild.1.en.html#flit_plugin

hello,I'm experiencing this issue, how can I fix it?

**Comment by 78w** [comment]
> hi， @stefanv， 你好， ， many thanks for your help.非常感谢您的帮助。 The[ package](https://tracker.debian.org/pkg/lazy-loader) has been entered into unstable on Debian. 该软件包已在 Debian 上进入不稳定状态。 thanks again~ 再次感谢~

do you had fix it?

**Comment by yuzibo** [comment]
> do you had fix it?

Not sure what happened around you,  but hope this helps:
https://salsa.debian.org/python-team/packages/lazy-loader

**Comment by 78w** [comment]
> > 你修好了吗？
> 
> 不知道你周围发生了什么，但希望这会有所帮助：https://salsa.debian.org/python-team/packages/lazy-loader

thanks,i  am already fix it
