### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by TortoiseHam** [scientific-python/lazy_loader#6]
Hi all, this isn't really an issue but I just wanted to let you know how amazingly useful this library is. A project I'm developing has a cli component for generating visualizations from logs, and your library is letting that part of our code run nearly 10x faster (anyone with a codebase importing tensorflow can probably reap similar benefits). The CLI went from almost unusably slow to being totally legitimate. Thank you for developing and releasing this.

**Comment by stefanv** [comment]
Thanks again for the kind words, @TortoiseHam. Closing this now prior to the upcoming release.
