### ISSUE TITLE
conda-forge doesn't have v0.3 

### ISSUE THREAD

**Issue by deppen8** [scientific-python/lazy_loader#73]
I was trying to use conda to install the [dev requirements for scikit-image](https://github.com/scikit-image/scikit-image/blob/main/requirements/default.txt) and noticed that it couldn't resolve `lazy_loader>=0.3`.

Looks like `v0.3` hasn't been added to `conda-forge` (https://anaconda.org/conda-forge/lazy_loader/files). I'm happy to make a PR with the few-line changes to the feedstock, but wanted to raise it here in case anything else in the feedstock needs to change too.

**Comment by bsipocz** [comment]
It looks like there are version update errors for conda-forge, I suppose the package's metadata or the recipe should be fixed first to make the conda packaging work.

(For details: https://conda-forge.org/status/#version_updates, then click on the lazy_loader logs.)

OTOH, `lazy_loader` is pure python, so you don't really need to rely on third party packaging but can use the official release from pypi.
