### ISSUE TITLE
Problem on running "production"

### ISSUE THREAD

**Issue by TomFreudenberg** [scientific-python/lazy_loader#86]
Hi, thanks for this project and your effort.

Using it on the boilerplate [Cedra](https://github.com/TomFreudenberg/cedra) I could manage to integrate dramatiq into a Cement app.

But running built project "in production" does not seem to work.

When I setup the project after checkout by:

```bash
python setup.py install
```

The lazy-loader doesn't seems to do it's job.

Running the same by using

```bash
python setup.py develop
```

all ist working fine.

You can test it with the above project, after checkout (inside project folder):

```bash
rm -rf .venv ; make virtualenv ; source .venv/bin/activate ; python setup.py install ; cedra --help
```

does not work

but instead 

```bash
rm -rf .venv ; make virtualenv ; source .venv/bin/activate ; python setup.py develop ; cedra --help
```

does work.

---

Any suggestions?

Cheers
Tom

**Comment by stefanv** [comment]
Hi @TomFreudenberg, we'd need a bit more information to debug here. What do you mean by "does not work"?

Note that `setup.py develop` is nowadays spelled `pip install --no-build-isolation -e .`, and `python setup.py install` becomes `pip install .`.

**Comment by stefanv** [comment]
Closing due to lack of information.
